### PR TITLE
lavalab-gen.py: introduce SFTP/SSHFS mount support in Worker

### PR DESCRIPTION
**Pull request by slawr**
Hi,

A couple of weeks ago I asked on IRC for feedback on how I was considering to add SFTP/SSHFS support to the Worker. The advice I got was to post a PR and here it is.

In my specific case I am administrating the Worker only. The task was limited to overcoming the issue of mount point handling in the volumes section of the docker-compose.

Tested as working on lava-docker commit b9e4d31 and rebased here for the PR to current master tip.

Regards

Steve

### CODE REVIEW

**Review by khilman — CHANGES_REQUESTED** [review]
This change isn't really specific to sshfs, it's just a way to add an additional mount point.  Could you generalize that instead just to be able to add additional volumes to mount?

Alternatively, if you want to support sshfs from the slave container itself, then you would need to add direct support for sshfs.

**Comment by slawr** [comment]
Thanks for the review Kevin. I had similar thoughts re making the wording more ssh specific or generic. That was my main motivation for asking on irc before getting to far with the work.

I actually had written in the PR description that I was not completely happy with the lack of specificity to ssh and that alternatively it could be generic. But rather than go onto writing an essay I deleted it in favour of just getting feedback.

I did consider bringing the SSHFS mounting within the container. That would enhance automation but would require configuration support to be added as well and having SSHFS control on the host would be more secure. Positives on both sides but in the end I decided to go with having the host handle it. Bringing it into the container might be a better match if the same was also done in the LAVA Master.

So I think I'll rework the PR then to make a generic mechanism for adding an additional volume to the docker-compose.

**Comment by slawr** [comment]
Hi @khilman I have not yet got back to this and am travelling soon for a couple of weeks. Meaning I will not get back to this till end of the month at the earlier. Would you prefer I close this and bring a new PR later to clean up your PR list or are you happy for it to stay open? My other thought was to apply a 'hold' label but I don't have the rights to set that.

**Comment by khilman** [comment]
It's fine with me if you leave it open.

**Comment by slawr** [comment]
Unfortunately the changes have remained low priority at the moment. So as this has been open for a while closing it for now to clean up the upstream PR list. Will re-open when something to update is ready.

**Pull request closed without merging**
