### PR TITLE
Upgrade to 2024.01

### PR DESCRIPTION
**Pull request by broonie**
Signed-off-by: Mark Brown <broonie@kernel.org>

### CODE REVIEW

**Review by aliceinwire — APPROVED** [review]
lgtm

**Comment by nuclearcat** [comment]
I assume anybody tested it?

**Comment by broonie** [comment]
I have this deployed in production, don't know about anyone else. At this point we should probably update to a more current release...

**Comment by montjoie** [comment]
I am sorry for the delay.
At least the selftests worked, I will start my basic upgrade path, I need to try it first on my test lab and my personal lab.

**Comment by nuclearcat** [comment]
Ok, merging, if there is any issue we can follow up.

**Pull request merged**
