### PR TITLE
Changing the ownership of /etc/lava-server/dispatcher-config/health-c…

### PR DESCRIPTION
**Pull request by mungaip**
…hecks to lavaserver.

This allows new healthcheck job submissions via API

### CODE REVIEW

**Comment by mungaip** [comment]
Although this issue is being fixed within lava: https://git.lavasoftware.org/lava/lava/merge_requests/140

**Review by khilman — CHANGES_REQUESTED** [review]
Thanks for submitting the fix!  Changes look good, but a couple requests.

Can you shorten the shortlog/subject so it fits?  Something like: "lava-master: fix permissions on health-checks", and then describe in more detail the problem you were having and how this fixes it in the changelog.

Also, please add a Signed-off-by?

**Comment by khilman** [comment]
Actually, since this is being fixed within LAVA, I'd prefer to use that instead of patching lava-docker.

@montjoie can you cherry-pick the LAVA fix mentioned above into lava-docker until we upgrade?

**Comment by montjoie** [comment]
We cannot backport it since it is a postinst (package) fix.
Anyway, even with LAVA will take care of right, we need to fix the permissions after the copy of our github repo.
Note that the commit miss a "-R" for chowning all the files inside

**Review by khilman — APPROVED** [review]

**Pull request merged**
